### ISSUE TITLE
关于洗牌算法

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [anotherso1a/spadger#1]
我看了看关于洗牌算法那里，不是很了解，能否详细讲解一下实现思路是什么，万分感谢

**Comment by anotherso1a** [comment]
>洗牌算法实际就是从一堆待洗的牌中随机抽出牌,然后将抽出的排置于新牌堆.
实现中使用了原数组末尾作为“新牌堆”,直接和随机抽到的排进行置换,这样可以节省一点内存.
